language: python
filter_secrets: false   # https://github.com/travis-ci/travis-ci/issues/8934

notifications:
  webhooks: https://coveralls.io/webhook

before_install:
  - deactivate  # virtual envs don't play nice with conda
  - export PYTHONUNBUFFERED=true  # immediately flush stdout to terminal
  - source devtools/ci/miniconda_install.sh
  - conda install -y pyyaml

install:
  - export OPS_ENV="openpathsampling-py${CONDA_PY}"
  - if [ -z "$MINIMAL" ] ; then source devtools/conda_install_reqs.sh; else pip install -r devtools/minimal.txt -r devtools/minimal_testing.txt; fi
  - pip install --no-deps -e .

before_script:
  - python --version
  - python -c "import openpathsampling"
  - source devtools/ci/git_hash.sh
  - conda info --envs
  - conda list

script:
  - source devtools/ci/pytests.sh
  - if [ -z "$MINIMAL" ] ; then source devtools/ci/ipythontests.sh; fi

  # Upload new docs
  - if [ -z "$MINIMAL" ] ; then bash -x devtools/ci/after_sucess.sh; fi

addons:
  apt:
    packages:
    - pandoc

env:
  global:
    - secure: "NJvoSrLNd2ZR3HluJjEqI36gD5lsucwIvgnYjNmM4cwnnA77aLV9FRYTwlLRZn3XY9FL8KOzL5l0amNzMD7sQrf7bWwWv7iCUBddH549q9RSgiuOugtodYJ6VaXi76hk1rOgcJpDoCj9wTCIlMtWibPUzr1QHmdihfdM2iA2kkE="
    - secure: "l9NJkZDD0ALhkErUvhRrreLsrcWErd+CXpWv8dxHGtkjemNx6CwVtyL+a30jz/QwMANSZbKll/cPK5yJQvuwDaWxja6UPLLKVNGtma+CmwKcIC/wwTwbMoxcS62fyLJ3kS0qR8oCQz2nCPKiYyRGADtPLWVMZckY1SJfNYcKuCM="
    - secure: "kb37xmsSV3pEnESnINzwlW2Cju/UFzA/G+m+NsihAwO8RMPZwKCrZK/rptgkUDACXJxom5M690WEukQkHnOt+OTrWhu7WKZgYeVuWUs2++RohYv/m5npaOHMMn+uYmF328v4PvPmXxbD02zzg5Tgdn82x8oa6J8BKX8ohOQ6Xpg="
  matrix:
    - CONDA_PY=3.7 MINIMAL=true
    - CONDA_PY=2.7
    - CONDA_PY=3.6
    - CONDA_PY=3.7
