language: python

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"

install:
  - deactivate
  # Sets up a MINIConda enviroment in the name of the selected python version
  - source devtools/ci/install.sh
  # Do not buffer output of python outputs but flush them directly to the terminal
  - export PYTHONUNBUFFERED=true

script:
  - echo travis_fold:start:conda.build.package
  - conda install --yes conda-build
  - conda build devtools/conda-recipe
  - echo travis_fold:end:conda.build.package

  # Run tests in _test environment
  - source activate _test
  - source devtools/ci/git_hash.sh
  - source devtools/ci/nosetests.sh
  - source devtools/ci/ipythontests.sh

  # Upload new docs
  - bash -x devtools/ci/after_sucess.sh

env:
  matrix:
    - python=2.7  CONDA_PY=27  CONDA_NPY=110
# - python=3.4  CONDA_PY=34  CONDA_NPY=110
# - python=3.5  CONDA_PY=35  CONDA_NPY=110

  global:
    # encrypted BINSTAR_TOKEN for push of dev package to binstar
    - secure: "Ou9KukGxCOdNWvEpr+9YrWTlB0xezu1mNV1gXtFjJ0RDIvzPRGUkpU7AUAdKwn6fUcbzq5E1y6rU9aG/QQe9YZkRHhPo585ZzieTNa0UxsyINk7XuwxL7MpRZijHCHFBvRVNrXkIh3CtmXvZS2ksAa8+FuYiO/lBbOMZ0nNAJac="
    - secure: "NJvoSrLNd2ZR3HluJjEqI36gD5lsucwIvgnYjNmM4cwnnA77aLV9FRYTwlLRZn3XY9FL8KOzL5l0amNzMD7sQrf7bWwWv7iCUBddH549q9RSgiuOugtodYJ6VaXi76hk1rOgcJpDoCj9wTCIlMtWibPUzr1QHmdihfdM2iA2kkE="
    - secure: "l9NJkZDD0ALhkErUvhRrreLsrcWErd+CXpWv8dxHGtkjemNx6CwVtyL+a30jz/QwMANSZbKll/cPK5yJQvuwDaWxja6UPLLKVNGtma+CmwKcIC/wwTwbMoxcS62fyLJ3kS0qR8oCQz2nCPKiYyRGADtPLWVMZckY1SJfNYcKuCM="
