on:
  pull_request:
    branches:
      - dev-2.0
  push:
    branches:
      - dev-2.0

defaults:
  run:
    shell: bash -l {0}

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    name: "Unit Tests"
    strategy:
      matrix:
        CONDA_PY:
          - 3.7
          #- 3.8
          #- 3.9
        MINIMAL: [""]
        include:
          - CONDA_PY: 3.7
            MINIMAL: "Minimal"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.CONDA_PY }}
      - name: "Install requirements"
        env:
          MINIMAL: ${{ matrix.MINIMAL }}
        run: |
          if [ -z "$MINIMAL" ] ; then
            source devtools/conda_install_reqs.sh
          else
            python -m pip install -r devtools/minimal.txt \
                                  -r devtools/minimal_testing.txt
          fi
      - name: "Install"
        run: python -m pip install --no-deps -e .
      - name: "Autorelease check"
        run: |
          python -m pip install autorelease
          python devtools/autorelease_check.py
      - name: "Versions"
        run: |
          conda info --envs
          conda list
      - name: "Unit tests"
        run: |
          python -c "import openpathsampling"
          py.test -vv -s --cov=openpathsampling --cov-report xml
      - name: "Test experimental features"
        if: matrix.MINIMAL == ''
        run: py.test -vv -s openpathsampling/experimental
      #- name: "Upload coverage"
        #run: bash <(curl -s https://codecov.io/bash)
